name: Light Bot

on:
  workflow_dispatch:

  schedule:

    # день (05:00–22:59 local UTC+2)
    - cron: "*/10 3-20 * * *"

    # 23:00 local
    - cron: "0 21 * * *"

    # 00:00–04:00 local
    - cron: "0 22-23 * * *"
    - cron: "0 0-2 * * *"

permissions:
  contents: write

jobs:

  bot:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install requests

      - run: python bot.py
